/*
 * File:           \\flexserver\software\swap\EdGonzalez\Codec_SidetoneSelect\CODEC_IC_1_PARAM.h
 *
 * Created:        Wednesday, June 29, 2016 5:19:34 PM
 * Description:    SmartSDR Audio Processor II:IC 1 parameter RAM definitions.
 *
 * This software is distributed in the hope that it will be useful,
 * but is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * This software may only be used to program products purchased from
 * Analog Devices for incorporation by you into audio products that
 * are intended for resale to audio product end users. This software
 * may not be distributed whole or in any part to third parties.
 *
 * Copyright ©2016 Analog Devices, Inc. All rights reserved.
 */
#ifndef __CODEC_IC_1_PARAM_H__
#define __CODEC_IC_1_PARAM_H__


/* Module Modulo Size - Modulo Size*/
#define MOD_MODULOSIZE_COUNT                           1
#define MOD_MODULOSIZE_DEVICE                          "IC1"
#define MOD_MODULOSIZE_MODULO_SIZE_ADDR                0
#define MOD_MODULOSIZE_MODULO_SIZE_FIXPT               0x00001000
#define MOD_MODULOSIZE_MODULO_SIZE_VALUE               SIGMASTUDIOTYPE_INTEGER_CONVERT(4096)
#define MOD_MODULOSIZE_MODULO_SIZE_TYPE                SIGMASTUDIOTYPE_INTEGER

/* Module SIG_GEN_SINE_1 - Sine Tone*/
#define MOD_SIGGEN_SIG_GEN_SINE_1_COUNT                3
#define MOD_SIGGEN_SIG_GEN_SINE_1_DEVICE               "IC1"
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_1_ALG0_MASK_ADDR 8
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_1_ALG0_MASK_FIXPT 0x000000FF
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_1_ALG0_MASK_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_1_ALG0_MASK_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_INCREMENT_ADDR  9
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_INCREMENT_FIXPT 0x00077777
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_INCREMENT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0583333333333333)
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_INCREMENT_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_ON_ADDR         10
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_ON_FIXPT        0x00800000
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_ON_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGGEN_SIG_GEN_SINE_1_ALG0_ON_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module SIG_GEN_SINE_2 - Sine Tone*/
#define MOD_SIGGEN_SIG_GEN_SINE_2_COUNT                3
#define MOD_SIGGEN_SIG_GEN_SINE_2_DEVICE               "IC1"
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_2_ALG0_MASK_ADDR 11
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_2_ALG0_MASK_FIXPT 0x000000FF
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_2_ALG0_MASK_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_SIGGEN_SIG_GEN_SINE_2_ALG0_MASK_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_INCREMENT_ADDR  12
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_INCREMENT_FIXPT 0x00144444
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_INCREMENT_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.158333333333333)
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_INCREMENT_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_ON_ADDR         13
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_ON_FIXPT        0x00000000
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_ON_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGGEN_SIG_GEN_SINE_2_ALG0_ON_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module SIG_GEN_TRIANGLE - Triangle wave*/
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_COUNT              7
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_DEVICE             "IC1"
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI0_ADDR     14
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI0_FIXPT    0x00000000
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI0_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI0_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI1_ADDR     15
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI1_FIXPT    0x00800000
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI1_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI1_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI2_ADDR     16
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI2_FIXPT    0x00000000
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI2_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI2_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI3_ADDR     17
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI3_FIXPT    0xFF800000
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI3_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1)
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_TRI3_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_STATIC_SIGGEN_SIG_GEN_TRIANGLE_ALG0_MASK_ADDR 18
#define MOD_STATIC_SIGGEN_SIG_GEN_TRIANGLE_ALG0_MASK_FIXPT 0x00000003
#define MOD_STATIC_SIGGEN_SIG_GEN_TRIANGLE_ALG0_MASK_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(3)
#define MOD_STATIC_SIGGEN_SIG_GEN_TRIANGLE_ALG0_MASK_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_FREQ_ADDR     19
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_FREQ_FIXPT    0x00077777
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_FREQ_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0583333333333333)
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_FREQ_TYPE     SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_ON_ADDR       20
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_ON_FIXPT      0x00800000
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_ON_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGGEN_SIG_GEN_TRIANGLE_ALG0_ON_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module SIG_GEN_SQUARE - Square wave*/
#define MOD_SIGGEN_SIG_GEN_SQUARE_COUNT                3
#define MOD_SIGGEN_SIG_GEN_SQUARE_DEVICE               "IC1"
#define MOD_STATIC_SIGGEN_SIG_GEN_SQUARE_ALG0_MASK_ADDR 21
#define MOD_STATIC_SIGGEN_SIG_GEN_SQUARE_ALG0_MASK_FIXPT 0x000000FF
#define MOD_STATIC_SIGGEN_SIG_GEN_SQUARE_ALG0_MASK_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_SIGGEN_SIG_GEN_SQUARE_ALG0_MASK_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_FREQ_ADDR       22
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_FREQ_FIXPT      0x00077777
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_FREQ_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0583333333333333)
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_FREQ_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_ON_ADDR         23
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_ON_FIXPT        0x00800000
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_ON_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGGEN_SIG_GEN_SQUARE_ALG0_ON_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module SIG_GEN_WHITENOISE - White Noise*/
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_COUNT            3
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_DEVICE           "IC1"
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_ENABLENOISE_ADDR 24
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_ENABLENOISE_FIXPT 0x00800000
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_ENABLENOISE_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_ENABLENOISE_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_ADDR   25
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_FIXPT  0x0005464B
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_VALUE  SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_TYPE   SIGMASTUDIOTYPE_INTEGER
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_ADDR   25
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_FIXPT  0x0005464B
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_VALUE  SIGMASTUDIOTYPE_INTEGER_CONVERT(345675)
#define MOD_SIGGEN_SIG_GEN_WHITENOISE_ALG0_SEED_TYPE   SIGMASTUDIOTYPE_INTEGER

/* Module CW_SIDETONE - Sine Tone*/
#define MOD_CW_SIDETONE_COUNT                          3
#define MOD_CW_SIDETONE_DEVICE                         "IC1"
#define MOD_STATIC_CW_SIDETONE_ALG0_MASK_ADDR          26
#define MOD_STATIC_CW_SIDETONE_ALG0_MASK_FIXPT         0x000000FF
#define MOD_STATIC_CW_SIDETONE_ALG0_MASK_VALUE         SIGMASTUDIOTYPE_INTEGER_CONVERT(255)
#define MOD_STATIC_CW_SIDETONE_ALG0_MASK_TYPE          SIGMASTUDIOTYPE_INTEGER
#define MOD_CW_SIDETONE_ALG0_INCREMENT_ADDR            27
#define MOD_CW_SIDETONE_ALG0_INCREMENT_FIXPT           0x00066666
#define MOD_CW_SIDETONE_ALG0_INCREMENT_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.05)
#define MOD_CW_SIDETONE_ALG0_INCREMENT_TYPE            SIGMASTUDIOTYPE_FIXPOINT
#define MOD_CW_SIDETONE_ALG0_ON_ADDR                   28
#define MOD_CW_SIDETONE_ALG0_ON_FIXPT                  0x00800000
#define MOD_CW_SIDETONE_ALG0_ON_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CW_SIDETONE_ALG0_ON_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module CW_KEY - On/Off Switch*/
#define MOD_CW_KEY_COUNT                               1
#define MOD_CW_KEY_DEVICE                              "IC1"
#define MOD_CW_KEY_ISON_ADDR                           29
#define MOD_CW_KEY_ISON_FIXPT                          0x00000000
#define MOD_CW_KEY_ISON_VALUE                          SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_CW_KEY_ISON_TYPE                           SIGMASTUDIOTYPE_FIXPOINT

/* Module CODEC_BINARY_VERSION_SET - DC Input Entry*/
#define MOD_CODEC_BINARY_VERSION_SET_COUNT             1
#define MOD_CODEC_BINARY_VERSION_SET_DEVICE            "IC1"
#define MOD_CODEC_BINARY_VERSION_SET_DCINPALG1_ADDR    30
#define MOD_CODEC_BINARY_VERSION_SET_DCINPALG1_FIXPT   0x00000404
#define MOD_CODEC_BINARY_VERSION_SET_DCINPALG1_VALUE   SIGMASTUDIOTYPE_INTEGER_CONVERT(1028)
#define MOD_CODEC_BINARY_VERSION_SET_DCINPALG1_TYPE    SIGMASTUDIOTYPE_INTEGER

/* Module CW_KEY_RX_MUTE - On/Off Switch*/
#define MOD_CW_KEY_RX_MUTE_COUNT                       1
#define MOD_CW_KEY_RX_MUTE_DEVICE                      "IC1"
#define MOD_CW_KEY_RX_MUTE_ISON_ADDR                   31
#define MOD_CW_KEY_RX_MUTE_ISON_FIXPT                  0x00800000
#define MOD_CW_KEY_RX_MUTE_ISON_VALUE                  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CW_KEY_RX_MUTE_ISON_TYPE                   SIGMASTUDIOTYPE_FIXPOINT

/* Module MIC_GAIN - Linear Gain*/
#define MOD_MIC_GAIN_COUNT                             1
#define MOD_MIC_GAIN_DEVICE                            "IC1"
#define MOD_MIC_GAIN_GAIN1940ALGNS4_ADDR               32
#define MOD_MIC_GAIN_GAIN1940ALGNS4_FIXPT              0x00800000
#define MOD_MIC_GAIN_GAIN1940ALGNS4_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MIC_GAIN_GAIN1940ALGNS4_TYPE               SIGMASTUDIOTYPE_FIXPOINT

/* Module LINE_GAIN - Linear Gain*/
#define MOD_LINE_GAIN_COUNT                            1
#define MOD_LINE_GAIN_DEVICE                           "IC1"
#define MOD_LINE_GAIN_GAIN1940ALGNS5_ADDR              33
#define MOD_LINE_GAIN_GAIN1940ALGNS5_FIXPT             0x00800000
#define MOD_LINE_GAIN_GAIN1940ALGNS5_VALUE             SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_LINE_GAIN_GAIN1940ALGNS5_TYPE              SIGMASTUDIOTYPE_FIXPOINT

/* Module CODEC_BINARY_VERSION - DSP Readback*/
#define MOD_CODEC_BINARY_VERSION_COUNT                 1
#define MOD_CODEC_BINARY_VERSION_DEVICE                "IC1"
#define MOD_CODEC_BINARY_VERSION_READBACKALGSIGMA2004_ADDR 34
#define MOD_CODEC_BINARY_VERSION_READBACKALGSIGMA2004_FIXPT 0x00000000
#define MOD_CODEC_BINARY_VERSION_READBACKALGSIGMA2004_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_CODEC_BINARY_VERSION_READBACKALGSIGMA2004_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module RX_MUTE - Mute*/
#define MOD_RX_MUTE_COUNT                              1
#define MOD_RX_MUTE_DEVICE                             "IC1"
#define MOD_RX_MUTE_MUTENOSLEWALG1MUTE_ADDR            35
#define MOD_RX_MUTE_MUTENOSLEWALG1MUTE_FIXPT           0x00800000
#define MOD_RX_MUTE_MUTENOSLEWALG1MUTE_VALUE           SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_RX_MUTE_MUTENOSLEWALG1MUTE_TYPE            SIGMASTUDIOTYPE_FIXPOINT

/* Module SIG_GEN_SELECT - Mono Switch Nx1*/
#define MOD_SIGGEN_SIG_GEN_SELECT_COUNT                4
#define MOD_SIGGEN_SIG_GEN_SELECT_DEVICE               "IC1"
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 36
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 37
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE2_MONOSWITCHNOSLEW_ADDR 38
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE2_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE2_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE2_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE3_MONOSWITCHNOSLEW_ADDR 39
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE3_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE3_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SIGGEN_SIG_GEN_SELECT_ALG0_STAGE3_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module CW_SIDETONE_RAMP - Single slew ext vol*/
#define MOD_CW_SIDETONE_RAMP_COUNT                     1
#define MOD_CW_SIDETONE_RAMP_DEVICE                    "IC1"
#define MOD_CW_SIDETONE_RAMP_EXTSWGAINDB1STEP_ADDR     40
#define MOD_CW_SIDETONE_RAMP_EXTSWGAINDB1STEP_FIXPT    0x00020000
#define MOD_CW_SIDETONE_RAMP_EXTSWGAINDB1STEP_VALUE    SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.015625)
#define MOD_CW_SIDETONE_RAMP_EXTSWGAINDB1STEP_TYPE     SIGMASTUDIOTYPE_FIXPOINT

/* Module SW vol 1 - Single slew ext vol*/
#define MOD_SWVOL1_COUNT                               1
#define MOD_SWVOL1_DEVICE                              "IC1"
#define MOD_SWVOL1_EXTSWGAINDB2STEP_ADDR               41
#define MOD_SWVOL1_EXTSWGAINDB2STEP_FIXPT              0x00020000
#define MOD_SWVOL1_EXTSWGAINDB2STEP_VALUE              SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.015625)
#define MOD_SWVOL1_EXTSWGAINDB2STEP_TYPE               SIGMASTUDIOTYPE_FIXPOINT

/* Module SIG_GEN_LEVEL - Single Volume*/
#define MOD_SIGGEN_SIG_GEN_LEVEL_COUNT                 1
#define MOD_SIGGEN_SIG_GEN_LEVEL_DEVICE                "IC1"
#define MOD_SIGGEN_SIG_GEN_LEVEL_GAIN1940ALGNS3_ADDR   42
#define MOD_SIGGEN_SIG_GEN_LEVEL_GAIN1940ALGNS3_FIXPT  0x00000346
#define MOD_SIGGEN_SIG_GEN_LEVEL_GAIN1940ALGNS3_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0001)
#define MOD_SIGGEN_SIG_GEN_LEVEL_GAIN1940ALGNS3_TYPE   SIGMASTUDIOTYPE_FIXPOINT

/* Module CW_MONITOR_LEVEL - Single Volume*/
#define MOD_CW_MONITOR_LEVEL_COUNT                     1
#define MOD_CW_MONITOR_LEVEL_DEVICE                    "IC1"
#define MOD_CW_MONITOR_LEVEL_GAIN1940ALGNS2_ADDR       43
#define MOD_CW_MONITOR_LEVEL_GAIN1940ALGNS2_FIXPT      0x00000346
#define MOD_CW_MONITOR_LEVEL_GAIN1940ALGNS2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0001)
#define MOD_CW_MONITOR_LEVEL_GAIN1940ALGNS2_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module INPUT_SOURCE - Mono Switch Nx1*/
#define MOD_INPUT_SOURCE_COUNT                         3
#define MOD_INPUT_SOURCE_DEVICE                        "IC1"
#define MOD_INPUT_SOURCE_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 44
#define MOD_INPUT_SOURCE_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_INPUT_SOURCE_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT_SOURCE_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT_SOURCE_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 45
#define MOD_INPUT_SOURCE_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_INPUT_SOURCE_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_INPUT_SOURCE_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_INPUT_SOURCE_ALG0_STAGE2_MONOSWITCHNOSLEW_ADDR 46
#define MOD_INPUT_SOURCE_ALG0_STAGE2_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_INPUT_SOURCE_ALG0_STAGE2_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_INPUT_SOURCE_ALG0_STAGE2_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module CW_MON_LEFT_PAN - Linear Gain*/
#define MOD_CW_MON_LEFT_PAN_COUNT                      1
#define MOD_CW_MON_LEFT_PAN_DEVICE                     "IC1"
#define MOD_CW_MON_LEFT_PAN_GAIN1940ALGNS11_ADDR       47
#define MOD_CW_MON_LEFT_PAN_GAIN1940ALGNS11_FIXPT      0x00800000
#define MOD_CW_MON_LEFT_PAN_GAIN1940ALGNS11_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CW_MON_LEFT_PAN_GAIN1940ALGNS11_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module CW_MON_RIGHT_PAN - Linear Gain*/
#define MOD_CW_MON_RIGHT_PAN_COUNT                     1
#define MOD_CW_MON_RIGHT_PAN_DEVICE                    "IC1"
#define MOD_CW_MON_RIGHT_PAN_GAIN1940ALGNS12_ADDR      48
#define MOD_CW_MON_RIGHT_PAN_GAIN1940ALGNS12_FIXPT     0x00800000
#define MOD_CW_MON_RIGHT_PAN_GAIN1940ALGNS12_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_CW_MON_RIGHT_PAN_GAIN1940ALGNS12_TYPE      SIGMASTUDIOTYPE_FIXPOINT

/* Module TX_LPF - General (2nd order)*/
#define MOD_TX_FILTER_TX_LPF_COUNT                     8
#define MOD_TX_FILTER_TX_LPF_DEVICE                    "IC1"
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B2_ADDR       49
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B2_FIXPT      0x001617AF
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.172597821798112)
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B2_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B1_ADDR       50
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B1_FIXPT      0x002C2F5E
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.345195643596225)
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B1_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B0_ADDR       51
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B0_FIXPT      0x001617AF
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B0_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.172597821798112)
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_B0_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A2_ADDR       52
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A2_FIXPT      0xFFDE41F5
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.263612196280223)
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A2_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A1_ADDR       53
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A1_FIXPT      0x00485957
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.565226554756296)
#define MOD_TX_FILTER_TX_LPF_ALG0_STAGE0_A1_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_LPF_ALG0_DATA_ADR_ADDR        54
#define MOD_TX_FILTER_TX_LPF_ALG0_DATA_ADR_FIXPT       0x00000045
#define MOD_TX_FILTER_TX_LPF_ALG0_DATA_ADR_VALUE       SIGMASTUDIOTYPE_INTEGER_CONVERT(69)
#define MOD_TX_FILTER_TX_LPF_ALG0_DATA_ADR_TYPE        SIGMASTUDIOTYPE_INTEGER
#define MOD_TX_FILTER_TX_LPF_ALG0_COEFF_ADR_ADDR       55
#define MOD_TX_FILTER_TX_LPF_ALG0_COEFF_ADR_FIXPT      0x00000034
#define MOD_TX_FILTER_TX_LPF_ALG0_COEFF_ADR_VALUE      SIGMASTUDIOTYPE_INTEGER_CONVERT(52)
#define MOD_TX_FILTER_TX_LPF_ALG0_COEFF_ADR_TYPE       SIGMASTUDIOTYPE_INTEGER
#define MOD_TX_FILTER_TX_LPF_ALG0_LOOP_ADDR            56
#define MOD_TX_FILTER_TX_LPF_ALG0_LOOP_FIXPT           0x00000001
#define MOD_TX_FILTER_TX_LPF_ALG0_LOOP_VALUE           SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_TX_FILTER_TX_LPF_ALG0_LOOP_TYPE            SIGMASTUDIOTYPE_INTEGER

/* Module TX_HPF - General (2nd order)*/
#define MOD_TX_FILTER_TX_HPF_COUNT                     8
#define MOD_TX_FILTER_TX_HPF_DEVICE                    "IC1"
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B2_ADDR       57
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B2_FIXPT      0x0078B6E7
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.943081810090252)
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B2_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B1_ADDR       58
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B1_FIXPT      0xFF0E9231
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-1.8861636201805)
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B1_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B0_ADDR       59
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B0_FIXPT      0x0078B6E7
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B0_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.943081810090252)
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_B0_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A2_ADDR       60
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A2_FIXPT      0xFF8B7578
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A2_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(-0.910477688147685)
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A2_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A1_ADDR       61
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A1_FIXPT      0x00F3E870
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.90553104294645)
#define MOD_TX_FILTER_TX_HPF_ALG0_STAGE0_A1_TYPE       SIGMASTUDIOTYPE_FIXPOINT
#define MOD_TX_FILTER_TX_HPF_ALG0_DATA_ADR_ADDR        62
#define MOD_TX_FILTER_TX_HPF_ALG0_DATA_ADR_FIXPT       0x0000004F
#define MOD_TX_FILTER_TX_HPF_ALG0_DATA_ADR_VALUE       SIGMASTUDIOTYPE_INTEGER_CONVERT(79)
#define MOD_TX_FILTER_TX_HPF_ALG0_DATA_ADR_TYPE        SIGMASTUDIOTYPE_INTEGER
#define MOD_TX_FILTER_TX_HPF_ALG0_COEFF_ADR_ADDR       63
#define MOD_TX_FILTER_TX_HPF_ALG0_COEFF_ADR_FIXPT      0x0000003C
#define MOD_TX_FILTER_TX_HPF_ALG0_COEFF_ADR_VALUE      SIGMASTUDIOTYPE_INTEGER_CONVERT(60)
#define MOD_TX_FILTER_TX_HPF_ALG0_COEFF_ADR_TYPE       SIGMASTUDIOTYPE_INTEGER
#define MOD_TX_FILTER_TX_HPF_ALG0_LOOP_ADDR            64
#define MOD_TX_FILTER_TX_HPF_ALG0_LOOP_FIXPT           0x00000001
#define MOD_TX_FILTER_TX_HPF_ALG0_LOOP_VALUE           SIGMASTUDIOTYPE_INTEGER_CONVERT(1)
#define MOD_TX_FILTER_TX_HPF_ALG0_LOOP_TYPE            SIGMASTUDIOTYPE_INTEGER

/* Module COMPANDER - Standard Peak*/
#define MOD_COMPANDER_COUNT                            37
#define MOD_COMPANDER_DEVICE                           "IC1"
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG10_ADDR 65
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG10_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG10_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG10_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG11_ADDR 66
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG11_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG11_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG11_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG12_ADDR 67
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG12_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG12_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG12_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG13_ADDR 68
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG13_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG13_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG13_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG14_ADDR 69
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG14_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG14_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG14_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG15_ADDR 70
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG15_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG15_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG15_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG16_ADDR 71
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG16_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG16_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG16_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG17_ADDR 72
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG17_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG17_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG17_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG18_ADDR 73
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG18_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG18_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG18_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG19_ADDR 74
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG19_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG19_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG19_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG110_ADDR 75
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG110_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG110_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG110_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG111_ADDR 76
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG111_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG111_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG111_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG112_ADDR 77
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG112_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG112_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG112_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG113_ADDR 78
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG113_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG113_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG113_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG114_ADDR 79
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG114_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG114_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG114_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG115_ADDR 80
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG115_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG115_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG115_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG116_ADDR 81
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG116_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG116_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG116_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG117_ADDR 82
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG117_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG117_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG117_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG118_ADDR 83
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG118_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG118_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG118_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG119_ADDR 84
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG119_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG119_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG119_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG120_ADDR 85
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG120_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG120_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG120_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG121_ADDR 86
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG121_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG121_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG121_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG122_ADDR 87
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG122_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG122_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG122_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG123_ADDR 88
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG123_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG123_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG123_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG124_ADDR 89
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG124_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG124_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG124_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG125_ADDR 90
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG125_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG125_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG125_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG126_ADDR 91
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG126_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG126_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG126_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG127_ADDR 92
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG127_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG127_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG127_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG128_ADDR 93
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG128_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG128_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG128_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG129_ADDR 94
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG129_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG129_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG129_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG130_ADDR 95
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG130_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG130_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG130_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG131_ADDR 96
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG131_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG131_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG131_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG132_ADDR 97
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG132_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG132_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG132_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG133_ADDR 98
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG133_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG133_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG133_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1HOLD_ADDR 99
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1HOLD_FIXPT 0x00000018
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(24)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1DECAY_ADDR 100
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1DECAY_FIXPT 0x00007B88
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00376991737763239)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1ATTENUATION_ADDR 101
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1ATTENUATION_FIXPT 0x00800000
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1ATTENUATION_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ALG0_STDPEAKINGCOMPRESSORALG1ATTENUATION_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PeakEnv1_2 - Envelope Peak*/
#define MOD_PEAKENV1_2_COUNT                           2
#define MOD_PEAKENV1_2_DEVICE                          "IC1"
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2HOLD_ADDR 108
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2HOLD_FIXPT 0x00000000
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2DECAY_ADDR 109
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2DECAY_FIXPT 0x0000007F
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.51909722222222E-05)
#define MOD_PEAKENV1_2_ALG0_MONOENVELOPEPEAKALG2DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module COMP_LEVEL_PEAK_IN - DSP Readback*/
#define MOD_COMP_LEVEL_PEAK_IN_COUNT                   1
#define MOD_COMP_LEVEL_PEAK_IN_DEVICE                  "IC1"
#define MOD_COMP_LEVEL_PEAK_IN_READBACKALGSIGMA2003_ADDR 110
#define MOD_COMP_LEVEL_PEAK_IN_READBACKALGSIGMA2003_FIXPT 0x00000000
#define MOD_COMP_LEVEL_PEAK_IN_READBACKALGSIGMA2003_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_COMP_LEVEL_PEAK_IN_READBACKALGSIGMA2003_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module POST_COMP_GAIN_1 - Linear Gain*/
#define MOD_POST_COMP_GAIN_1_COUNT                     1
#define MOD_POST_COMP_GAIN_1_DEVICE                    "IC1"
#define MOD_POST_COMP_GAIN_1_GAIN1940ALGNS1_ADDR       111
#define MOD_POST_COMP_GAIN_1_GAIN1940ALGNS1_FIXPT      0x00800000
#define MOD_POST_COMP_GAIN_1_GAIN1940ALGNS1_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_POST_COMP_GAIN_1_GAIN1940ALGNS1_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module PeakEnv1_3 - Envelope Peak*/
#define MOD_PEAKENV1_3_COUNT                           2
#define MOD_PEAKENV1_3_DEVICE                          "IC1"
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3HOLD_ADDR 112
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3HOLD_FIXPT 0x00000000
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3DECAY_ADDR 113
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3DECAY_FIXPT 0x0000007F
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.51909722222222E-05)
#define MOD_PEAKENV1_3_ALG0_MONOENVELOPEPEAKALG3DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module POST_COMP_GAIN_2 - Linear Gain*/
#define MOD_POST_COMP_GAIN_2_COUNT                     1
#define MOD_POST_COMP_GAIN_2_DEVICE                    "IC1"
#define MOD_POST_COMP_GAIN_2_GAIN1940ALGNS6_ADDR       114
#define MOD_POST_COMP_GAIN_2_GAIN1940ALGNS6_FIXPT      0x00800000
#define MOD_POST_COMP_GAIN_2_GAIN1940ALGNS6_VALUE      SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_POST_COMP_GAIN_2_GAIN1940ALGNS6_TYPE       SIGMASTUDIOTYPE_FIXPOINT

/* Module COMP_LEVEL_PEAK_OUT - DSP Readback*/
#define MOD_COMP_LEVEL_PEAK_OUT_COUNT                  1
#define MOD_COMP_LEVEL_PEAK_OUT_DEVICE                 "IC1"
#define MOD_COMP_LEVEL_PEAK_OUT_READBACKALGSIGMA2005_ADDR 115
#define MOD_COMP_LEVEL_PEAK_OUT_READBACKALGSIGMA2005_FIXPT 0x00000000
#define MOD_COMP_LEVEL_PEAK_OUT_READBACKALGSIGMA2005_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_COMP_LEVEL_PEAK_OUT_READBACKALGSIGMA2005_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module COMPANDER_ENABLE - Mono Switch Nx1*/
#define MOD_COMPANDER_ENABLE_COUNT                     2
#define MOD_COMPANDER_ENABLE_DEVICE                    "IC1"
#define MOD_COMPANDER_ENABLE_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 116
#define MOD_COMPANDER_ENABLE_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_COMPANDER_ENABLE_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_COMPANDER_ENABLE_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_COMPANDER_ENABLE_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 117
#define MOD_COMPANDER_ENABLE_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_COMPANDER_ENABLE_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_COMPANDER_ENABLE_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module MODE_BYPASS_EQ_COMP - Mono Switch Nx1*/
#define MOD_MODE_BYPASS_EQ_COMP_COUNT                  2
#define MOD_MODE_BYPASS_EQ_COMP_DEVICE                 "IC1"
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 118
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 119
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MODE_BYPASS_EQ_COMP_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module METER_SELECT - Mono Switch Nx1*/
#define MOD_METER_SELECT_COUNT                         2
#define MOD_METER_SELECT_DEVICE                        "IC1"
#define MOD_METER_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_ADDR 120
#define MOD_METER_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_METER_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_METER_SELECT_ALG0_STAGE0_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_METER_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_ADDR 121
#define MOD_METER_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_METER_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_METER_SELECT_ALG0_STAGE1_MONOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module Threshold_Gain - Linear Gain*/
#define MOD_THRESHOLD_GAIN_COUNT                       1
#define MOD_THRESHOLD_GAIN_DEVICE                      "IC1"
#define MOD_THRESHOLD_GAIN_GAIN1940ALGNS7_ADDR         122
#define MOD_THRESHOLD_GAIN_GAIN1940ALGNS7_FIXPT        0x00599999
#define MOD_THRESHOLD_GAIN_GAIN1940ALGNS7_VALUE        SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.7)
#define MOD_THRESHOLD_GAIN_GAIN1940ALGNS7_TYPE         SIGMASTUDIOTYPE_FIXPOINT

/* Module VOICE_MONITOR_LEVEL - Single Volume*/
#define MOD_VOICE_MONITOR_LEVEL_COUNT                  1
#define MOD_VOICE_MONITOR_LEVEL_DEVICE                 "IC1"
#define MOD_VOICE_MONITOR_LEVEL_GAIN1940ALGNS8_ADDR    123
#define MOD_VOICE_MONITOR_LEVEL_GAIN1940ALGNS8_FIXPT   0x00000346
#define MOD_VOICE_MONITOR_LEVEL_GAIN1940ALGNS8_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.0001)
#define MOD_VOICE_MONITOR_LEVEL_GAIN1940ALGNS8_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module AvgEnv1 - Running Average*/
#define MOD_AVGENV1_COUNT                              3
#define MOD_AVGENV1_DEVICE                             "IC1"
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_ADDR  124
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_FIXPT 0x000025BF
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00115195553816894)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1RMS_TYPE  SIGMASTUDIOTYPE_FIXPOINT
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_ADDR 125
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_FIXPT 0x00000000
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_ADDR 126
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_FIXPT 0x0000016C
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(4.34027777777778E-05)
#define MOD_AVGENV1_ALG0_MONORUNAVGDETECTALG1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module PeakEnv1 - Envelope Peak*/
#define MOD_PEAKENV1_COUNT                             2
#define MOD_PEAKENV1_DEVICE                            "IC1"
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1HOLD_ADDR 127
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1HOLD_FIXPT 0x00000000
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(0)
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1DECAY_ADDR 128
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1DECAY_FIXPT 0x0000007F
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1.51909722222222E-05)
#define MOD_PEAKENV1_ALG0_MONOENVELOPEPEAKALG1DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module 1 X RTA1 - Single Level Detector*/
#define MOD_1XRTA1_COUNT                               4
#define MOD_1XRTA1_DEVICE                              "IC1"
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001TCONST_ADDR 129
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001TCONST_FIXPT 0x00009D91
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001TCONST_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.00480857655249389)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001TCONST_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001HOLD_ADDR 130
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001HOLD_FIXPT 0x000000F0
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001HOLD_VALUE SIGMASTUDIOTYPE_INTEGER_CONVERT(240)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001HOLD_TYPE SIGMASTUDIOTYPE_INTEGER
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001DECAY_ADDR 131
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001DECAY_FIXPT 0x00000E38
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001DECAY_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0.000434027777777778)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001DECAY_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001_ADDR   132
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001_VALUE  SIGMASTUDIOTYPE_10_18_CONVERT(0)
#define MOD_1XRTA1_ALG0_SINGLEBANDLEVELDETS2001_TYPE   SIGMASTUDIOTYPE_10_18

/* Module SB_MON_LEFT_PAN - Linear Gain*/
#define MOD_SB_MON_LEFT_PAN_COUNT                      1
#define MOD_SB_MON_LEFT_PAN_DEVICE                     "IC1"
#define MOD_SB_MON_LEFT_PAN_GAIN1940ALGNS9_ADDR        133
#define MOD_SB_MON_LEFT_PAN_GAIN1940ALGNS9_FIXPT       0x00800000
#define MOD_SB_MON_LEFT_PAN_GAIN1940ALGNS9_VALUE       SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SB_MON_LEFT_PAN_GAIN1940ALGNS9_TYPE        SIGMASTUDIOTYPE_FIXPOINT

/* Module SB_MON_RIGHT_PAN - Linear Gain*/
#define MOD_SB_MON_RIGHT_PAN_COUNT                     1
#define MOD_SB_MON_RIGHT_PAN_DEVICE                    "IC1"
#define MOD_SB_MON_RIGHT_PAN_GAIN1940ALGNS10_ADDR      134
#define MOD_SB_MON_RIGHT_PAN_GAIN1940ALGNS10_FIXPT     0x00800000
#define MOD_SB_MON_RIGHT_PAN_GAIN1940ALGNS10_VALUE     SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_SB_MON_RIGHT_PAN_GAIN1940ALGNS10_TYPE      SIGMASTUDIOTYPE_FIXPOINT

/* Module MONITOR_VOICE_CW - Stereo Switch Nx2*/
#define MOD_MONITOR_VOICE_CW_COUNT                     2
#define MOD_MONITOR_VOICE_CW_DEVICE                    "IC1"
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE0_STEREOSWITCHNOSLEW_ADDR 135
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE0_STEREOSWITCHNOSLEW_FIXPT 0x00000000
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE0_STEREOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE0_STEREOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE1_STEREOSWITCHNOSLEW_ADDR 136
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE1_STEREOSWITCHNOSLEW_FIXPT 0x00800000
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE1_STEREOSWITCHNOSLEW_VALUE SIGMASTUDIOTYPE_FIXPOINT_CONVERT(1)
#define MOD_MONITOR_VOICE_CW_ALG0_STAGE1_STEREOSWITCHNOSLEW_TYPE SIGMASTUDIOTYPE_FIXPOINT

/* Module MIC_LEVEL_AVG - DSP Readback*/
#define MOD_MIC_LEVEL_AVG_COUNT                        1
#define MOD_MIC_LEVEL_AVG_DEVICE                       "IC1"
#define MOD_MIC_LEVEL_AVG_READBACKALGSIGMA2002_ADDR    137
#define MOD_MIC_LEVEL_AVG_READBACKALGSIGMA2002_FIXPT   0x00000000
#define MOD_MIC_LEVEL_AVG_READBACKALGSIGMA2002_VALUE   SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIC_LEVEL_AVG_READBACKALGSIGMA2002_TYPE    SIGMASTUDIOTYPE_FIXPOINT

/* Module MIC_LEVEL_PEAK - DSP Readback*/
#define MOD_MIC_LEVEL_PEAK_COUNT                       1
#define MOD_MIC_LEVEL_PEAK_DEVICE                      "IC1"
#define MOD_MIC_LEVEL_PEAK_READBACKALGSIGMA2001_ADDR   138
#define MOD_MIC_LEVEL_PEAK_READBACKALGSIGMA2001_FIXPT  0x00000000
#define MOD_MIC_LEVEL_PEAK_READBACKALGSIGMA2001_VALUE  SIGMASTUDIOTYPE_FIXPOINT_CONVERT(0)
#define MOD_MIC_LEVEL_PEAK_READBACKALGSIGMA2001_TYPE   SIGMASTUDIOTYPE_FIXPOINT

#endif
