#!/bin/sh

DESC="Load Microburst Sound Modules"

do_start() {
    modprobe snd-soc-davinci
    modprobe snd-soc-microburst
    modprobe snd-soc-davinci-mcasp
}

do_stop() {
    rmmod snd-soc-davinci-mcasp
    rmmod snd-soc-microburst
    rmmod snd-soc-davinci
}

case "$1" in
  start)
	echo "Starting $DESC"
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
